%% ==============================================================
% PERIODIC HILL: SPALDING vs ML
% WALL SHEAR STRESS / SKIN FRICTION
%
% Reads wallShearStressMean (the fieldAverage'd field, NOT the instantaneous
% wallShearStress - see system/functions' own comment on why: for LES, a single
% instantaneous snapshot is a chaotic turbulent instant, not the converged mean
% quantity Spalding's law actually describes, so comparing against it isn't a
% fair or meaningful comparison) from the "hills" patch, averaged over
% Hansen/Yang/Abkar's own Tf=200 flow-through-time window (see controlDict/
% system/functions), and compares the signed streamwise/tangential skin-friction
% coefficient.
%
% OpenFOAM wallShearStress dimensions:
%
%       [0 2 -2 0 0 0 0]
%
% Therefore wallShearStress (and its time-average) is kinematic:
%
%       tau_w / rho
%
% With Ub = 1 m/s:
%
%       Cf = 2*tau_w,t
%
% ==============================================================

clear;
clc;
close all;

%% ==============================================================
% CASE SETTINGS
% ==============================================================
% endTime = 2000 (200 flow-through times of averaging + ~22 FTT spin-up, per
% controlDict) - was '0.1'/'0.09', an early, barely-past-the-initial-transient
% instant under the OLD (wrong) endTime=0.5 convention.

cases(1).name  = 'Spalding';
cases(1).dir   = 'spaldingSim';
cases(1).time  = '2000';
cases(1).color = [0.0000 0.4470 0.7410];

cases(2).name  = 'ML';
cases(2).dir   = 'mlSim';
cases(2).time  = '2000';
cases(2).color = [0.8500 0.3250 0.0980];

%% ==============================================================
% FLOW SETTINGS
% ==============================================================

Ub = 1.0;

%% ==============================================================
% MAIN FIGURE
% ==============================================================

figure('Color','w');
hold on;

%% ==============================================================
% PLOT HILL GEOMETRY
% ==============================================================

xhHill = linspace(0,9,1000);

ywHill = arrayfun( ...
    @hillHeight, ...
    xhHill);

% Offset the hill slightly downward so that it does not obscure
% the Cf curve when Cf is close to zero.
plot( ...
    xhHill, ...
    zeros(size(xhHill)), ...
    'k-', ...
    'LineWidth',2.0, ...
    'HandleVisibility','off');

%% ==============================================================
% READ AND PLOT EACH CASE
% ==============================================================

for c = 1:length(cases)

    fprintf('\n');
    fprintf('============================================\n');
    fprintf('Reading %s\n',cases(c).name);
    fprintf('============================================\n');

    %% ----------------------------------------------------------
    % File
    % -----------------------------------------------------------

    file = fullfile( ...
        cases(c).dir, ...
        cases(c).time, ...
        'wallShearStressMean');

    %% ----------------------------------------------------------
    % Read hill wall shear
    % -----------------------------------------------------------

    [tauRaw,~,~] = readWallShearStress(file);

    %% ----------------------------------------------------------
    % Number of wall faces
    % -----------------------------------------------------------

    fprintf( ...
        'Wall shear vectors = %d\n', ...
        size(tauRaw,1));

    %% ----------------------------------------------------------
    % Read wall-face geometry
    %
    % This uses the OpenFOAM patch data generated by the
    % wallShearStress field if available.
    %
    % At this point, we use a uniform x distribution as an
    % initial fallback only.
    % -----------------------------------------------------------

    nFaces = size(tauRaw,1);

    %% ----------------------------------------------------------
    % IMPORTANT:
    %
    % wallShearStress itself does not contain the wall-face
    % coordinates. If your raw wallShearStress data are ordered
    % consistently with the hill patch, x/h can be reconstructed
    % from the 120 x 60 structured patch.
    % -----------------------------------------------------------

    Nx = 120;
    Nz = 60;

    if nFaces ~= Nx*Nz

        error( ...
            ['Expected %d hill faces (=120*60), but found %d ' ...
             'in %s'], ...
            Nx*Nz, ...
            nFaces, ...
            file);

    end

    %% ----------------------------------------------------------
    % Reshape wall shear
    % -----------------------------------------------------------

    tau = reshape( ...
        tauRaw, ...
        [Nx Nz 3]);

    %% ----------------------------------------------------------
    % Build x coordinates of wall faces
    %
    % Your mesh contains 120 cells in x, so face locations are
    % approximately:
    %
    %   x/h = 0, 0.075, ..., 8.925
    %
    % -----------------------------------------------------------

    xFace = ((0:Nx-1) + 0.5)*(9/Nx);

    %% ----------------------------------------------------------
    % Tangential shear
    %
    % Hill tangent:
    %
    %       t = (1,dy/dx)
    %
    % normalized.
    %
    % tau_t = tau_x*t_x + tau_y*t_y
    %
    % -----------------------------------------------------------

    tauTangential = zeros(Nx,1);

    %% ----------------------------------------------------------
    % Spanwise average
    % -----------------------------------------------------------

    for i = 1:Nx

        xh = xFace(i);

        %% Hill derivative

        dx = 1e-5;

        yp = hillHeight(xh + dx);
        ym = hillHeight(xh - dx);

        dydx = (yp - ym)/(2*dx);

        %% Tangent vector

        tx = 1/sqrt(1 + dydx^2);
        ty = dydx/sqrt(1 + dydx^2);

        %% All z faces at this x

        tauX = squeeze(tau(i,:,1));
        tauY = squeeze(tau(i,:,2));

        %% Tangential wall shear

        tauT = tauX*tx + tauY*ty;

        %% Spanwise average

        tauTangential(i) = mean(tauT);

    end

    %% ----------------------------------------------------------
    % Skin friction coefficient
    %
    % OpenFOAM field is tau/rho
    %
    % Cf = (tau/rho)/(0.5 Ub^2)
    % -----------------------------------------------------------

    Cf = tauTangential/(0.5*Ub^2);

    %% ----------------------------------------------------------
    % Store results
    % -----------------------------------------------------------

    cases(c).x = xFace;
    cases(c).Cf = Cf;

    %% ----------------------------------------------------------
    % Plot
    % -----------------------------------------------------------

    plot( ...
        xFace, ...
        Cf, ...
        'Color',cases(c).color, ...
        'LineWidth',1.8, ...
        'DisplayName',cases(c).name);

end

%% ==============================================================
% ZERO LINE
% ==============================================================

yline( ...
    0, ...
    'k--', ...
    'LineWidth',1.0, ...
    'HandleVisibility','off');

%% ==============================================================
% FORMAT
% ==============================================================

xlabel('$x/h$', ...
    'Interpreter','latex');

ylabel('$C_f$', ...
    'Interpreter','latex');

ax = gca;
ax.YAxis.Exponent = 0;
ytickformat('%.4f');

title( ...
    'Skin-friction coefficient: Spalding vs ML', ...
    'Interpreter','latex');

xlim([0 9]);

legend( ...
    'Location','best');

grid on;
box on;

set(gca, ...
    'FontSize',11, ...
    'LineWidth',1);

%% ==============================================================
% PRINT SEPARATION / REATTACHMENT ESTIMATES
% ==============================================================

fprintf('\n');
fprintf('============================================\n');
fprintf('Separation / reattachment estimates\n');
fprintf('============================================\n');

for c = 1:length(cases)

    x = cases(c).x;
    Cf = cases(c).Cf;

    %% Find sign changes

    idx = find(Cf(1:end-1).*Cf(2:end) <= 0);

    fprintf('\n%s:\n',cases(c).name);

    if isempty(idx)

        fprintf('  No zero crossings detected.\n');

    else

        for j = 1:length(idx)

            i = idx(j);

            %% Linear interpolation

            xZero = ...
                x(i) ...
                - Cf(i)*(x(i+1)-x(i)) ...
                /(Cf(i+1)-Cf(i));

            fprintf( ...
                '  Cf = 0 at x/h = %.4f\n', ...
                xZero);

        end

    end

end

%% ==============================================================
% FUNCTION: READ WALL SHEAR STRESS
% ==============================================================

function [V, patch, text] = readWallShearStress(filename)

    %% ----------------------------------------------------------
    % Open file
    % ----------------------------------------------------------

    fid = fopen(filename,'r');

    if fid == -1

        error( ...
            'Could not open %s', ...
            filename);

    end

    text = fread(fid,'*char')';

    fclose(fid);

    %% ----------------------------------------------------------
    % Find internalField
    % ----------------------------------------------------------

    idx = strfind( ...
        text, ...
        'internalField');

    if isempty(idx)

        error( ...
            'Could not find internalField in %s', ...
            filename);

    end

    idx = idx(1);

    localText = text(idx:end);

    %% ----------------------------------------------------------
    % Find internal field
    % ----------------------------------------------------------

    token = 'nonuniform List<vector>';

    idx2 = strfind( ...
        localText, ...
        token);

    %% ----------------------------------------------------------
    % Case 1: uniform internal field
    %
    % wallShearStress is normally zero in the volume, with
    % actual values supplied on the boundary.
    % ----------------------------------------------------------

    if isempty(idx2)

        error( ...
            ['Could not find nonuniform internalField. ' ...
             'This reader expects the wallShearStress file ' ...
             'to contain nonuniform boundary values.']);

    end

    idx2 = idx + idx2(1) - 1;

    afterType = ...
        text(idx2 + length(token):end);

    %% ----------------------------------------------------------
    % Number of vectors
    % ----------------------------------------------------------

    countMatch = regexp( ...
        afterType, ...
        '^\s*(\d+)', ...
        'tokens', ...
        'once');

    if isempty(countMatch)

        error( ...
            'Could not determine vector count in %s', ...
            filename);

    end

    N = str2double( ...
        countMatch{1});

    %% ----------------------------------------------------------
    % Find list opening parenthesis
    % ----------------------------------------------------------

    pRel = strfind( ...
        afterType, ...
        '(');

    if isempty(pRel)

        error( ...
            'Could not find vector list in %s', ...
            filename);

    end

    p = ...
        idx2 + length(token) + pRel(1) - 1;

    dataText = text(p+1:end);

    %% ----------------------------------------------------------
    % Extract vectors
    % ----------------------------------------------------------

    expr = [ ...
        '\(\s*' ...
        '([-+0-9.eE]+)\s+' ...
        '([-+0-9.eE]+)\s+' ...
        '([-+0-9.eE]+)\s*\)' ];

    tokens = regexp( ...
        dataText, ...
        expr, ...
        'tokens');

    if length(tokens) < N

        error( ...
            'Expected %d vectors but found %d in %s', ...
            N,length(tokens),filename);

    end

    tokens = tokens(1:N);

    V = zeros(N,3);

    for i = 1:N

        V(i,1) = str2double(tokens{i}{1});
        V(i,2) = str2double(tokens{i}{2});
        V(i,3) = str2double(tokens{i}{3});

    end

    patch = [];

end

%% ==============================================================
% FUNCTION: EXACT PERIODIC HILL GEOMETRY
% ==============================================================

function yw = hillHeight(xh)

    %% Convert x/h -> original coordinate in mm

    x_mm = mod(xh,9.0)*28.0;

    %% Mirror second half

    if x_mm > 198.0

        xs = 252.0 - x_mm;

    else

        xs = x_mm;

    end

    %% Piecewise polynomial

    if xs >= 0 && xs < 9

        y_mm = min( ...
            28.0, ...
            28.0 ...
          + 0.000000000000E+00*xs ...
          + 6.775070969851E-03*xs.^2 ...
          - 2.124527775800E-03*xs.^3);

    elseif xs >= 9 && xs < 14

        y_mm = ...
            2.507355893131E+01 ...
          + 9.754803562315E-01*xs ...
          - 1.016116352781E-01*xs.^2 ...
          + 1.889794677828E-03*xs.^3;

    elseif xs >= 14 && xs < 20

        y_mm = ...
            2.579601052357E+01 ...
          + 8.206693007457E-01*xs ...
          - 9.055370274339E-02*xs.^2 ...
          + 1.626510569859E-03*xs.^3;

    elseif xs >= 20 && xs < 30

        y_mm = ...
            4.046435022819E+01 ...
          - 1.379581654948E+00*xs ...
          + 1.945884504128E-02*xs.^2 ...
          - 2.070318932190E-04*xs.^3;

    elseif xs >= 30 && xs < 40

        y_mm = ...
            1.792461334664E+01 ...
          + 8.743920332081E-01*xs ...
          - 5.567361123058E-02*xs.^2 ...
          + 6.277731764683E-04*xs.^3;

    elseif xs >= 40 && xs < 54

        y_mm = max( ...
            0.0, ...
            5.639011190988E+01 ...
          - 2.010520359035E+00*xs ...
          + 1.644919857549E-02*xs.^2 ...
          + 2.674976141766E-05*xs.^3);

    else

        y_mm = 0;

    end

    %% Normalize

    yw = y_mm/28.0;

end