%% ============================================================
% NACA 0012 LES WALL SHEAR
%
% 3D surface data -> spanwise/area averaged distributions
%
% Case:
%   naca0012LES_aoa10
%
% Input:
%   comparison_results/wallShearStress.csv
%
% CSV:
%   x/c
%   y/c
%   z/c
%   tau_w_Pa
%   tau_x_Pa
%   tau_y_Pa
%   tau_z_Pa
%   Cf
%   surface_area_m2
%
% Upper:
%   z/c > 0
%
% Lower:
%   z/c < 0
%
% ============================================================

clear;
close all;
clc;

%% ============================================================
% SETTINGS
% ============================================================

caseDir = 'comparison_results';

wallFile = fullfile( ...
    caseDir, ...
    'wallShearStress.csv');

exportDir = fullfile( ...
    caseDir, ...
    'figures');

AoA = 10;

% Number of streamwise stations
NX = 500;

% Round x/c before grouping
xRoundDigits = 8;

% Marker spacing
markerStep = 20;

%% ============================================================
% PUBLICATION SETTINGS
% ============================================================

paperWidth = 3.25;
paperHeight = 2.35;

fontName = 'Times New Roman';

axisFontSize = 8;
labelFontSize = 9;
titleFontSize = 9;
legendFontSize = 7;

lineWidth = 1.2;
markerSize = 3.0;

if ~isfolder(exportDir)
    mkdir(exportDir);
end

%% ============================================================
% CHECK FILE
% ============================================================

if ~isfile(wallFile)
    error( ...
        'Could not find:\n%s', ...
        wallFile);
end

%% ============================================================
% READ DATA
% ============================================================

data = readmatrix(wallFile);

data = data(all(isfinite(data),2),:);

if size(data,2) < 9
    error( ...
        ['Expected 9 columns:\n' ...
         'x/c,y/c,z/c,tau_w,tau_x,tau_y,tau_z,Cf,area']);
end

x = data(:,1);
y = data(:,2);
z = data(:,3);

tauw = data(:,4);
taux = data(:,5);
tauy = data(:,6);
tauz = data(:,7);

Cf = data(:,8);
area = data(:,9);

fprintf('\n');
fprintf('============================================================\n');
fprintf('NACA 0012 LES WALL SHEAR\n');
fprintf('============================================================\n');

fprintf('\nCase:\n');
fprintf('  %s\n',caseDir);

fprintf('\nAoA = %.1f deg\n',AoA);

fprintf('\nRaw surface points = %d\n',length(x));

fprintf('Raw surface area   = %.8e m^2\n',sum(area));

%% ============================================================
% UPPER / LOWER
% ============================================================

upper = z > 0;
lower = z < 0;

fprintf('\nRaw upper points = %d\n',sum(upper));
fprintf('Raw lower points = %d\n',sum(lower));

%% ============================================================
% AREA-WEIGHTED SPANWISE AVERAGING
% ============================================================

[ ...
    xu, ...
    tauwu, ...
    taxu, ...
    tazu, ...
    Cfu] = averageSurface( ...
        x(upper), ...
        y(upper), ...
        z(upper), ...
        tauw(upper), ...
        taux(upper), ...
        tauz(upper), ...
        Cf(upper), ...
        area(upper), ...
        NX, ...
        xRoundDigits);

[ ...
    xl, ...
    tauwl, ...
    taxl, ...
    tazl, ...
    Cfl] = averageSurface( ...
        x(lower), ...
        y(lower), ...
        z(lower), ...
        tauw(lower), ...
        taux(lower), ...
        tauz(lower), ...
        Cf(lower), ...
        area(lower), ...
        NX, ...
        xRoundDigits);

fprintf('\nAveraged streamwise stations:\n');
fprintf('  Upper = %d\n',length(xu));
fprintf('  Lower = %d\n',length(xl));

%% ============================================================
% MARKER INDICES
% ============================================================

iU = 1:markerStep:length(xu);
iL = 1:markerStep:length(xl);

if ~isempty(iU) && iU(end) ~= length(xu)
    iU(end+1) = length(xu);
end

if ~isempty(iL) && iL(end) ~= length(xl)
    iL(end+1) = length(xl);
end

%% ============================================================
% PLOT tau_w
% ============================================================

fig = createPaperFigure( ...
    paperWidth, ...
    paperHeight, ...
    fontName);

ax = axes(fig);

hold(ax,'on');
box(ax,'on');
grid(ax,'on');

plot( ...
    ax, ...
    xu, ...
    tauwu, ...
    '-', ...
    'LineWidth',lineWidth, ...
    'Marker','o', ...
    'MarkerSize',markerSize, ...
    'MarkerIndices',iU, ...
    'DisplayName','Upper');

plot( ...
    ax, ...
    xl, ...
    tauwl, ...
    '-', ...
    'LineWidth',lineWidth, ...
    'Marker','s', ...
    'MarkerSize',markerSize, ...
    'MarkerIndices',iL, ...
    'DisplayName','Lower');

formatAxes( ...
    ax, ...
    '$\tau_w$ [Pa]', ...
    sprintf('Wall shear stress, $\\alpha=%g^\\circ$',AoA), ...
    fontName, ...
    axisFontSize, ...
    labelFontSize, ...
    titleFontSize);

legend( ...
    ax, ...
    'Location','best', ...
    'FontSize',legendFontSize, ...
    'Box','off');

exportgraphics( ...
    fig, ...
    fullfile(exportDir,'wallShear_tau_w_AoA10.pdf'), ...
    'ContentType','vector', ...
    'BackgroundColor','white');

%% ============================================================
% PLOT tau_x
% ============================================================

fig = createPaperFigure( ...
    paperWidth, ...
    paperHeight, ...
    fontName);

ax = axes(fig);

hold(ax,'on');
box(ax,'on');
grid(ax,'on');

plot( ...
    ax, ...
    xu, ...
    taxu, ...
    '-', ...
    'LineWidth',lineWidth, ...
    'Marker','o', ...
    'MarkerSize',markerSize, ...
    'MarkerIndices',iU, ...
    'DisplayName','Upper');

plot( ...
    ax, ...
    xl, ...
    taxl, ...
    '-', ...
    'LineWidth',lineWidth, ...
    'Marker','s', ...
    'MarkerSize',markerSize, ...
    'MarkerIndices',iL, ...
    'DisplayName','Lower');

formatAxes( ...
    ax, ...
    '$\tau_x$ [Pa]', ...
    sprintf('$\\tau_x$, $\\alpha=%g^\\circ$',AoA), ...
    fontName, ...
    axisFontSize, ...
    labelFontSize, ...
    titleFontSize);

legend( ...
    ax, ...
    'Location','best', ...
    'FontSize',legendFontSize, ...
    'Box','off');

exportgraphics( ...
    fig, ...
    fullfile(exportDir,'wallShear_tau_x_AoA10.pdf'), ...
    'ContentType','vector', ...
    'BackgroundColor','white');

%% ============================================================
% PLOT tau_z
% ============================================================

fig = createPaperFigure( ...
    paperWidth, ...
    paperHeight, ...
    fontName);

ax = axes(fig);

hold(ax,'on');
box(ax,'on');
grid(ax,'on');

plot( ...
    ax, ...
    xu, ...
    tazu, ...
    '-', ...
    'LineWidth',lineWidth, ...
    'Marker','o', ...
    'MarkerSize',markerSize, ...
    'MarkerIndices',iU, ...
    'DisplayName','Upper');

plot( ...
    ax, ...
    xl, ...
    tazl, ...
    '-', ...
    'LineWidth',lineWidth, ...
    'Marker','s', ...
    'MarkerSize',markerSize, ...
    'MarkerIndices',iL, ...
    'DisplayName','Lower');

formatAxes( ...
    ax, ...
    '$\tau_z$ [Pa]', ...
    sprintf('$\\tau_z$, $\\alpha=%g^\\circ$',AoA), ...
    fontName, ...
    axisFontSize, ...
    labelFontSize, ...
    titleFontSize);

legend( ...
    ax, ...
    'Location','best', ...
    'FontSize',legendFontSize, ...
    'Box','off');

exportgraphics( ...
    fig, ...
    fullfile(exportDir,'wallShear_tau_z_AoA10.pdf'), ...
    'ContentType','vector', ...
    'BackgroundColor','white');

%% ============================================================
% PLOT Cf
% ============================================================

fig = createPaperFigure( ...
    paperWidth, ...
    paperHeight, ...
    fontName);

ax = axes(fig);

hold(ax,'on');
box(ax,'on');
grid(ax,'on');

plot( ...
    ax, ...
    xu, ...
    Cfu, ...
    '-', ...
    'LineWidth',lineWidth, ...
    'Marker','o', ...
    'MarkerSize',markerSize, ...
    'MarkerIndices',iU, ...
    'DisplayName','Upper');

plot( ...
    ax, ...
    xl, ...
    Cfl, ...
    '-', ...
    'LineWidth',lineWidth, ...
    'Marker','s', ...
    'MarkerSize',markerSize, ...
    'MarkerIndices',iL, ...
    'DisplayName','Lower');

yline( ...
    ax, ...
    0, ...
    ':k', ...
    'HandleVisibility','off');

formatAxes( ...
    ax, ...
    '$C_f$', ...
    sprintf('$C_f$, $\\alpha=%g^\\circ$',AoA), ...
    fontName, ...
    axisFontSize, ...
    labelFontSize, ...
    titleFontSize);

legend( ...
    ax, ...
    'Location','best', ...
    'FontSize',legendFontSize, ...
    'Box','off');

exportgraphics( ...
    fig, ...
    fullfile(exportDir,'wallShear_Cf_AoA10.pdf'), ...
    'ContentType','vector', ...
    'BackgroundColor','white');

%% ============================================================
% 2x2 OVERVIEW
% ============================================================

fig = figure( ...
    'Color','w', ...
    'Units','inches', ...
    'Position',[1 1 6.5 4.75], ...
    'PaperUnits','inches', ...
    'PaperPosition',[0 0 6.5 4.75], ...
    'PaperSize',[6.5 4.75]);

tl = tiledlayout( ...
    fig, ...
    2, ...
    2, ...
    'TileSpacing','compact', ...
    'Padding','compact');

% tau_w
ax = nexttile(tl,1);
hold(ax,'on');
box(ax,'on');
grid(ax,'on');

plot(ax,xu,tauwu,'-o', ...
    'LineWidth',1.0, ...
    'MarkerSize',2.5, ...
    'MarkerIndices',iU);

plot(ax,xl,tauwl,'-s', ...
    'LineWidth',1.0, ...
    'MarkerSize',2.5, ...
    'MarkerIndices',iL);

formatSmallAxes(ax,'$\tau_w$ [Pa]',fontName);

% tau_x
ax = nexttile(tl,2);
hold(ax,'on');
box(ax,'on');
grid(ax,'on');

plot(ax,xu,taxu,'-o', ...
    'LineWidth',1.0, ...
    'MarkerSize',2.5, ...
    'MarkerIndices',iU);

plot(ax,xl,taxl,'-s', ...
    'LineWidth',1.0, ...
    'MarkerSize',2.5, ...
    'MarkerIndices',iL);

formatSmallAxes(ax,'$\tau_x$ [Pa]',fontName);

% tau_z
ax = nexttile(tl,3);
hold(ax,'on');
box(ax,'on');
grid(ax,'on');

plot(ax,xu,tazu,'-o', ...
    'LineWidth',1.0, ...
    'MarkerSize',2.5, ...
    'MarkerIndices',iU);

plot(ax,xl,tazl,'-s', ...
    'LineWidth',1.0, ...
    'MarkerSize',2.5, ...
    'MarkerIndices',iL);

formatSmallAxes(ax,'$\tau_z$ [Pa]',fontName);

% Cf
ax = nexttile(tl,4);
hold(ax,'on');
box(ax,'on');
grid(ax,'on');

plot(ax,xu,Cfu,'-o', ...
    'LineWidth',1.0, ...
    'MarkerSize',2.5, ...
    'MarkerIndices',iU);

plot(ax,xl,Cfl,'-s', ...
    'LineWidth',1.0, ...
    'MarkerSize',2.5, ...
    'MarkerIndices',iL);

yline(ax,0,':k','HandleVisibility','off');

formatSmallAxes(ax,'$C_f$',fontName);

exportgraphics( ...
    fig, ...
    fullfile(exportDir,'wallShear_AoA10_overview.pdf'), ...
    'ContentType','vector', ...
    'BackgroundColor','white');

%% ============================================================
% SAVE AREA-AVERAGED DATA
% ============================================================

upperTable = table( ...
    xu, ...
    tauwu, ...
    taxu, ...
    tazu, ...
    Cfu, ...
    'VariableNames',{ ...
    'x_c', ...
    'tau_w_Pa', ...
    'tau_x_Pa', ...
    'tau_z_Pa', ...
    'Cf'});

lowerTable = table( ...
    xl, ...
    tauwl, ...
    taxl, ...
    tazl, ...
    Cfl, ...
    'VariableNames',{ ...
    'x_c', ...
    'tau_w_Pa', ...
    'tau_x_Pa', ...
    'tau_z_Pa', ...
    'Cf'});

writetable( ...
    upperTable, ...
    fullfile(exportDir,'wallShear_upper_averaged.csv'));

writetable( ...
    lowerTable, ...
    fullfile(exportDir,'wallShear_lower_averaged.csv'));

%% ============================================================
% SUMMARY
% ============================================================

fprintf('\n');
fprintf('============================================================\n');
fprintf('SPANWISE AVERAGING COMPLETE\n');
fprintf('============================================================\n');

fprintf('\nRaw points:\n');
fprintf('  Upper = %d\n',sum(upper));
fprintf('  Lower = %d\n',sum(lower));

fprintf('\nAveraged points:\n');
fprintf('  Upper = %d\n',length(xu));
fprintf('  Lower = %d\n',length(xl));

fprintf('\nGenerated figures:\n');
fprintf('  wallShear_tau_w_AoA10.pdf\n');
fprintf('  wallShear_tau_x_AoA10.pdf\n');
fprintf('  wallShear_tau_z_AoA10.pdf\n');
fprintf('  wallShear_Cf_AoA10.pdf\n');
fprintf('  wallShear_AoA10_overview.pdf\n');

fprintf('\nAveraged data:\n');
fprintf('  wallShear_upper_averaged.csv\n');
fprintf('  wallShear_lower_averaged.csv\n');

fprintf('\nOutput directory:\n');
fprintf('  %s\n',exportDir);

fprintf('\nDone.\n');

%% ============================================================
% LOCAL FUNCTION:
% AREA-WEIGHTED SPANWISE AVERAGE
% ============================================================

function [xOut,varargout] = averageSurface( ...
    x, ...
    y, ...
    z, ...
    tauw, ...
    taux, ...
    tauz, ...
    Cf, ...
    area, ...
    NX, ...
    roundDigits)

    % ---------------------------------------------------------
    % Remove invalid values
    % ---------------------------------------------------------

    valid = ...
        isfinite(x) & ...
        isfinite(y) & ...
        isfinite(z) & ...
        isfinite(tauw) & ...
        isfinite(taux) & ...
        isfinite(tauz) & ...
        isfinite(Cf) & ...
        isfinite(area) & ...
        area > 0;

    x = x(valid);
    y = y(valid);
    z = z(valid);
    tauw = tauw(valid);
    taux = taux(valid);
    tauz = tauz(valid);
    Cf = Cf(valid);
    area = area(valid);

    % ---------------------------------------------------------
    % Use rounded x/c to avoid floating-point differences
    % between neighboring spanwise cells.
    % ---------------------------------------------------------

    xGroup = round(x,roundDigits);

    uniqueX = unique(xGroup);

    % If there are many exact x locations, use them directly.
    % Otherwise bin them into NX stations.
    % ---------------------------------------------------------

    if length(uniqueX) <= NX

        xStations = uniqueX;

    else

        xStations = linspace( ...
            min(x), ...
            max(x), ...
            NX);

    end

    % ---------------------------------------------------------
    % Allocate
    % ---------------------------------------------------------

    xOut = [];
    tauwOut = [];
    tauxOut = [];
    tauzOut = [];
    CfOut = [];

    % ---------------------------------------------------------
    % Average
    % ---------------------------------------------------------

    for i = 1:length(xStations)

        if length(uniqueX) <= NX

            mask = xGroup == xStations(i);

        else

            if i == length(xStations)

                mask = ...
                    x >= xStations(i-1) & ...
                    x <= xStations(i);

            elseif i == 1

                mask = ...
                    x >= xStations(i) & ...
                    x < xStations(i+1);

            else

                left = ...
                    0.5 * ...
                    (xStations(i-1)+xStations(i));

                right = ...
                    0.5 * ...
                    (xStations(i)+xStations(i+1));

                mask = ...
                    x >= left & ...
                    x < right;

            end

        end

        if ~any(mask)
            continue;
        end

        A = area(mask);

        if sum(A) <= 0
            continue;
        end

        xMean = sum(x(mask).*A) / sum(A);

        tauwMean = ...
            sum(tauw(mask).*A) / sum(A);

        tauxMean = ...
            sum(taux(mask).*A) / sum(A);

        tauzMean = ...
            sum(tauz(mask).*A) / sum(A);

        CfMean = ...
            sum(Cf(mask).*A) / sum(A);

        xOut(end+1,1) = xMean;
        tauwOut(end+1,1) = tauwMean;
        tauxOut(end+1,1) = tauxMean;
        tauzOut(end+1,1) = tauzMean;
        CfOut(end+1,1) = CfMean;

    end

    % ---------------------------------------------------------
    % Sort
    % ---------------------------------------------------------

    [xOut,order] = sort(xOut);

    tauwOut = tauwOut(order);
    tauxOut = tauxOut(order);
    tauzOut = tauzOut(order);
    CfOut = CfOut(order);

    % ---------------------------------------------------------
    % Return
    % ---------------------------------------------------------

    varargout{1} = tauwOut;
    varargout{2} = tauxOut;
    varargout{3} = tauzOut;
    varargout{4} = CfOut;

end

%% ============================================================
% LOCAL FUNCTION:
% PAPER FIGURE
% ============================================================

function fig = createPaperFigure( ...
    width, ...
    height, ...
    fontName)

    fig = figure( ...
        'Color','w', ...
        'Units','inches', ...
        'Position',[1 1 width height], ...
        'PaperUnits','inches', ...
        'PaperPosition',[0 0 width height], ...
        'PaperSize',[width height], ...
        'InvertHardcopy','off');

    set(fig, ...
        'DefaultAxesFontName',fontName, ...
        'DefaultTextFontName',fontName);

end

%% ============================================================
% LOCAL FUNCTION:
% FORMAT AXES
% ============================================================

function formatAxes( ...
    ax, ...
    ylabelText, ...
    titleText, ...
    fontName, ...
    axisFontSize, ...
    labelFontSize, ...
    titleFontSize)

    set(ax, ...
        'FontName',fontName, ...
        'FontSize',axisFontSize, ...
        'LineWidth',0.75, ...
        'TickDir','out', ...
        'Layer','top');

    xlabel( ...
        ax, ...
        '$x/c$', ...
        'Interpreter','latex', ...
        'FontSize',labelFontSize);

    ylabel( ...
        ax, ...
        ylabelText, ...
        'Interpreter','latex', ...
        'FontSize',labelFontSize);

    title( ...
        ax, ...
        titleText, ...
        'Interpreter','latex', ...
        'FontSize',titleFontSize);

    xlim(ax,[0 1]);

end

%% ============================================================
% LOCAL FUNCTION:
% SMALL AXES
% ============================================================

function formatSmallAxes( ...
    ax, ...
    ylabelText, ...
    fontName)

    set(ax, ...
        'FontName',fontName, ...
        'FontSize',7, ...
        'LineWidth',0.6, ...
        'TickDir','out', ...
        'Layer','top');

    xlabel( ...
        ax, ...
        '$x/c$', ...
        'Interpreter','latex', ...
        'FontSize',8);

    ylabel( ...
        ax, ...
        ylabelText, ...
        'Interpreter','latex', ...
        'FontSize',8);

    xlim(ax,[0 1]);

end